export function createInitialState() {
  return {
    time: 0,
    lastTs: 0,
    creeps: [],
    structures: [],
    projectiles: [],
    effects: [],
    winner: null,
    spawnTimer: 0,
    enemyThinkTimer: 0,
    player: null,
    enemy: null,
    rafId: 0,
    input: {
      mouseX: 0,
      mouseY: 0,
      moving: false,
    },
    uiMessageTimer: 0,
    message: '',
    gateWasVulnerable: false,
    cameraShake: 0,
    level: 1,
    selectedHeroClass: "crimson_hunter",
    heroSelectOpen: false,
    skillHazards: [],
    mapHoles: [],
    level3HoleSpawnTimer: 0,
    level3FluxX: 0,
    level3FluxDir: 1,
    escortPayload: null,
    relics: [],
    relicSpawnTimer: 0,
    soulCoins: [],
    denySoulCoinBonus: 12,
    crashed: false,
    crashReason: "",
  };
}
